### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by sabliao** [chentsulin/sweetalert-react#14]
When starting webpack to run our reactjs project w/ your sweetalert-react library (to get those nice alerts), we can't get it to work for the same reason why we can't get the original sweetalert library to work:

```
/vagrant/app/node_modules/sweetalert/lib/modules/utils.js:37
  if (window.console) {
      ^

ReferenceError: window is not defined
    at Object.logStr (/vagrant/app/node_modules/sweetalert/lib/modules/utils.js:37:7)
    at Object.<anonymous> (/vagrant/app/node_modules/sweetalert/lib/sweetalert.js:301:48)
    at Module._compile (module.js:413:34)
    at Module._extensions..js (module.js:422:10)
    at Object.require.extensions.(anonymous function) [as .js] (/vagrant/app/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/vagrant/app/node_modules/sweetalert-react/lib/SweetAlert.js:17:19)
```

window is called in the original sweetalert file, and calling an import of the sweetalert-react library calls an import on 'sweetalert', which fails the start of the webpack build. How were you able to get past this issue?

**Comment by chentsulin** [comment]
`window` should be defined in browser. Are you using sweetalert in server rendering?
At this moment, it will not work in server rendering. Need some of refactoring there: https://github.com/t4t5/sweetalert/blob/master/dev/sweetalert.es6.js#L310

**Comment by sabliao** [comment]
Yeah, I think webpack or react is doing server-side rendering too. :/

**Comment by sebastian-hsu** [comment]
@chentsulin, I am still confusing how to deal with this issue, should I include this refactoring into my server side code?

**Comment by chentsulin** [comment]
I think the best solution at this moment is to avoid render sweetalert on the server entirely. There are so many `window` reference in sweetalert source code..

**Comment by sebastian-hsu** [comment]
Thanks, I just don't know how to avoid server rendering for only 1 item. Anyway, I did [https://github.com/webpack/react-starter/issues/37#issuecomment-95715239](https://github.com/webpack/react-starter/issues/37#issuecomment-95715239) to solve my problem.
